### ISSUE TITLE
能不能把sql也贴出来啊

### ISSUE THREAD

**Issue by learninginb** [upcyiban/keep-going#1]

**Comment by sky-admin** [comment]
https://spring.io/guides/gs/accessing-data-jpa/
看下这个，不需要SQL

**Comment by learninginb** [comment]
感谢

2019-04-22 

许祺 



发件人：Huanyu Li <notifications@github.com>
发送时间：2019-04-22 11:32
主题：Re: [upcyiban/keep-going] 能不能把sql也贴出来啊 (#1)
收件人："upcyiban/keep-going"<keep-going@noreply.github.com>
抄送："xuqimm"<674954347@QQ.COM>,"Author"<author@noreply.github.com>

https://spring.io/guides/gs/accessing-data-jpa/
看下这个，不需要SQL
